### ISSUE TITLE
documentation link is dead

### ISSUE THREAD

**Issue by PeterAaser** [ucb-bar/chisel2-deprecated#745]
Links to documentation repo is dead :(

**Comment by shunshou** [comment]
Hmm... looks like you're not the first to think ucb-bar/chisel is still being actively worked on. We probably need to have that in bigger letters somewhere...

The new and improved (and actively in development) version of Chisel sits @ https://github.com/freechipsproject/chisel3

There's quite a bit of documentation @ https://github.com/freechipsproject/chisel3/wiki

(and more to come).

**Comment by PeterAaser** [comment]
I'd love to use chisel 3!
Sadly, it's for a course, and none of the teachers have used chisel 3, and we have a lot of quite advanced chisel 2 libraries that we use. While I don't expect any feature requests or issues to be followed up it would be pretty nice to just have the tutorial docs. I did find them in a fork so it's not a pressing issue, but it would be handy to have them here :)

**Comment by edwardcwang** [comment]
I'm interested to hear that you're using it for a class. Is the course from the https://en.wikipedia.org/wiki/Norwegian_University_of_Science_and_Technology by any chance? I'd just be curious to see what the class is about./if you have a course website, and how you're using Chisel in it.

**Comment by PeterAaser** [comment]
It's for the "computer design project" where students form groups of 7-8 people and basically create a computer from scratch. I attended two years ago, and we created a chip that took in video via HDMI, performed convolution on the videoframes on an FPGA programmed with chisel, and outputted the result on another HDMI port. We even had 8 layer PCBs we designed printed in china, and it also came with an ARM cortex IO processor for flashing and programming the convolution accelerator. The course is worth twice that of a regular course (and quadruple the effort!!)

**Comment by ucbjrl** [comment]
@PeterAaser, could you point out the dead links?

**Comment by PeterAaser** [comment]
@ucbjrl the one linking to docs:
https://github.com/ucb-bar/chisel-doc

**Comment by ucbjrl** [comment]
That's a private repo. Where did you see the link to it?

**Comment by PeterAaser** [comment]
@ucbjrl it's in the readme under the Documentation header.

**Comment by schoeberl** [comment]
As I was recently teaching a Chisel tutorial and for various reasons I’m still using version 2. Therefore, I’ve “rescued” the Chisel 2 documentation for the tutorial:

https://github.com/schoeberl/chisel2-doc <https://github.com/schoeberl/chisel2-doc>

Cheers,
Martin

**Comment by abhishek42** [comment]
The link to chisel 2.2 tutorials at https://chisel.eecs.berkeley.edu/2.2.0/getting-started.html takes to the tutorials written for Chisel3. If i am not wrong the tutorials will differ for both chisel 2.2 and chisel3 , right? 

The directory structure mentioned on the link above for chisel tutorials is different from what is used in chisel3 tutorials. I am some project which was built on chisel2.2 and hence need to learn it. If anyone has a link to chisel2.2 tutorials, it would help out people starting with it.

@schoeberl By any chance, did you rescue chisel2.2 tutorials as well?

**Comment by chick** [comment]
I think the problem you are describing is that this [chisel-tutorial](https://github.com/ucb-bar/chisel-tutorial) link takes you to the latest branch which is chisel3.  The chisel2 code is still there under [chisel2 branch](https://github.com/ucb-bar/chisel-tutorial/tree/chisel2).  There probably ought to be a separate release tagged.

**Comment by abhishek42** [comment]
ya. Apologies. I found it after posting it here.
